//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace szaipa2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Ip { get; set; }
        public string Nation { get; set; }
        public string Porvince { get; set; }
        public string Ctiy { get; set; }
        public string DC { get; set; }
    }
}
