//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace szaipa2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int VisitCount { get; set; }
        public string Class { get; set; }
        public string RArt { get; set; }
        public string RWork { get; set; }
        public string RNews { get; set; }
        public string CoverTitle { get; set; }
        public string ImgsTitle { get; set; }
        public string Add { get; set; }
        public string OtherInf { get; set; }
    }
}
