//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace szaipa2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public int Id { get; set; }
        public string ArtistNameCN { get; set; }
        public string ArtistNameEN { get; set; }
        public string Sex { get; set; }
        public string Path { get; set; }
        public string UserContent { get; set; }
        public string Nation { get; set; }
        public string City { get; set; }
        public string Title { get; set; }
        public Nullable<int> WorkCount { get; set; }
        public string EditRecord { get; set; }
        public string Deeds { get; set; }
        public string Honor { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string FlieInf { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public string Activity { get; set; }
        public string Color1 { get; set; }
        public string Color2 { get; set; }
        public string DeedsThings { get; set; }
        public string DeedsYear { get; set; }
        public string Introduction { get; set; }
        public string Position { get; set; }
    }
}
