//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace szaipa2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string NameCN { get; set; }
        public string NameEN { get; set; }
        public string Business { get; set; }
        public string CEO { get; set; }
        public string ImgPath { get; set; }
        public string FilePath { get; set; }
        public string Address { get; set; }
        public string EditRecord { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string Activity { get; set; }
    }
}
