//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace szaipa2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int VistiTotal { get; set; }
        public int NewsVisit { get; set; }
        public int ArtVisit { get; set; }
        public int WorksVisit { get; set; }
        public int CompanyVisit { get; set; }
        public string OperationRecord { get; set; }
    }
}
