//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace szaipa2022.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SzaipaEntities : DbContext
    {
        public SzaipaEntities()
            : base("name=SzaipaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessData> AccessData { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Artist> Artist { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Diary> Diary { get; set; }
        public virtual DbSet<MonthData> MonthData { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<Works> Works { get; set; }
        public virtual DbSet<WorksTag> WorksTag { get; set; }
        public virtual DbSet<ArtNews> ArtNews { get; set; }
        public virtual DbSet<Auction> Auction { get; set; }
        public virtual DbSet<Fav> Fav { get; set; }
        public virtual DbSet<Public> Public { get; set; }
    }
}
