//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace szaipa2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public int Id { get; set; }
        public string TitleCN { get; set; }
        public string TitleEN { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string FolderName { get; set; }
        public int MaxImg { get; set; }
        public string LogoPath { get; set; }
        public string CoverPath { get; set; }
        public int ReadCount { get; set; }
        public string EditRecord { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Location { get; set; }
        public string zhuban { get; set; }
        public string chengban { get; set; }
        public string xieban { get; set; }
    }
}
