//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace szaipa2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongouWorks
    {
        public int id { get; set; }
        public int Atristid { get; set; }
        public string AtristidName { get; set; }
        public string Title { get; set; }
        public string ImgPath { get; set; }
        public string Size { get; set; }
        public int VisityCount { get; set; }
        public string Type { get; set; }
        public string CreationDate { get; set; }
        public int HotCount { get; set; }
    }
}
